# Generated by Django 4.2.2 on 2023-06-14 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_alter_userinformation_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinformation",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_information",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
